CREATE table public.dgefp_contrat_employeur_assure AS 
select 
  ddadtcontrat.id, 
  id_employeur_assure, 
  date_debut_contrat, 
  statut_conventionnel, 
  statut_rc, 
  pcs_ese, 
  code_complement_pcs_ese, 
  libelle_emploi, 
  nature_contrat, 
  dispositif_politique, 
  ddadtcontrat.num_contrat, 
  date_fin_previsionnelle, 
  unite_mesure, 
  quotite_categorie, 
  quotite, 
  modalite_temps, 
  complement_base, 
  ccn, 
  regime_maladie, 
  id_lieu_travail, 
  regime_vieillesse, 
  motif_recours, 
  code_caisse_conges_payes, 
  travailleur_etranger, 
  taux_frais_professionnels, 
  statut_emploi, 
  motif_exclusion_dsn, 
  code_affectation_ac, 
  num_interne, 
  type_gestion_ac, 
  date_adhesion, 
  date_convention_gestion, 
  num_convention_gestion, 
  code_gestionnaire_risque, 
  code_metier, 
  regime_risque_accident_travail, 
  code_risque_accident_travail, 
  positionnement_cc, 
  code_statut_categoriel_apecita, 
  taux_accident_travail, 
  salarie_tpartiel_cotis_tplein, 
  remuneration_pourboir, 
  id_lieu_etab_utilisateur, 
  num_certification_sociale, 
  num_label, 
  num_licence_entrep_spectacle, 
  num_objet_spectacle, 
  statut_organisateur_spectacle, 
  date_fin_contrat, 
  motif_rupture, 
  dernier_jour_travaille, 
  ddadtcontrat.date_dernieres_infos, 
  mod_decl_fin_cont_usage, 
  activite_partielle, 
  statut_boeth, 
  mise_a_dispo_ext, 
  cat_classement_finale, 
  college_cnieg, 
  complement_dispositif_public, 
  id_contrat_em, 
  ddadtcontrat.mois_declaration, 
  grade, 
  finess_geographique, 
  echelon, 
  coef_hierarchique, 
  flag_traitement_vue_donnee, 
  ddadtemployeur_assure.date_creation as ddadtemployeur_assure_date_creation, 
  ddadtemployeur_assure.date_dernieres_modif as ddadtemployeur_assure_date_dernieres_modif, 
  ddadtemployeur.siret, 
  ddadtemployeur.et_enseigne, 
  ddadtemployeur.et_code_apet, 
  ddadtemployeur.et_ad_num_et_libelle_voie, 
  ddadtemployeur.et_ad_code_postal, 
  ddadtemployeur.et_ad_localite, 
  ddadtemployeur.et_ad_code_pays, 
  ddadtemployeur.et_ad_code_distrib_etranger, 
  ddadtemployeur.et_ad_complement_localisation, 
  ddadtemployeur.et_ad_service_distrib, 
  ddadtemployeur.et_ad_code_insee_commune, 
  ddadtemployeur.et_effectif_fin_periode, 
  ddadtemployeur.et_remuneration_expatries, 
  ddadtemployeur.et_nature_juridique, 
  ddadtemployeur.et_date_cloture, 
  ddadtemployeur.et_categorie_juridique, 
  ddadtemployeur.siren, 
  ddadtemployeur.nic_siege, 
  ddadtemployeur.en_code_apen, 
  ddadtemployeur.en_raison_sociale, 
  ddadtemployeur.en_ad_num_et_libelle_voie, 
  ddadtemployeur.en_ad_code_postal, 
  ddadtemployeur.en_ad_localite, 
  ddadtemployeur.en_ad_code_pays, 
  ddadtemployeur.en_ad_code_distrib_etranger, 
  ddadtemployeur.en_ad_complement_localisation, 
  ddadtemployeur.en_ad_service_distrib, 
  ddadtemployeur.en_effectif_moyen, 
  ddadtemployeur.en_code_implantation, 
  ddadtemployeur.en_date_debut_cvae, 
  ddadtemployeur.en_date_fin_cvae, 
  ddadtemployeur.mois_declaration as ddadtemployeur_mois_declaration, 
  ddadtemployeur.et_code_conv_collec_principale, 
  ddadtemployeur.et_operateur_competence, 
  ddadtemployeur.en_code_conv_collec_applicable, 
  ddadtassure.num_immatriculation, 
  ddadtassure.type_immatriculation, 
  ddadtassure.nir_certifie, 
  ddadtassure.nom_usage, 
  ddadtassure.nom_famille, 
  ddadtassure.prenoms, 
  ddadtassure.sexe, 
  ddadtassure.date_naissance, 
  ddadtassure.date_dernieres_infos as ddadtassure_date_dernieres_infos, 
  ddadtassure.lieu_naissance, 
  ddadtassure.codification_ue, 
  ddadtassure.code_departement_naissance, 
  ddadtassure.code_pays_naissance, 
  ddadtassure.adresse_mail, 
  ddadtassure.nb_enfants_a_charge, 
  ddadtassure.date_naissance_certif_sngi, 
  ddadtassure.nom_famille_certif_sngi, 
  ddadtassure.prenoms_certif_sngi, 
  ddadtassure.nom_marital_certif_sngi, 
  ddadtassure.code_resultat_certif_sngi, 
  ddadtassure.indice_certif_sngi, 
  ddadtassure.commune_naissance_sngi, 
  ddadtassure.code_dpt_naissance_sngi, 
  ddadtassure.code_pays_naissance_sngi, 
  ddadtassure.date_nir_certif_sngi, 
  ddadtassure.immat_certifiee, 
  ddadtassure.niveau_formation_plus_eleve, 
  ddadtassure.niveau_diplome_prepare, 
  ddadtassure.date_deces_certif_sngi, 
  ddadtassure.num_immatriculation_chiffree, 
  ddadtassure.immat_certifiee_chiffree 
from 
  public.ddadtcontrat 
  inner join (
    SELECT 
      num_contrat, 
      max(date_dernieres_infos) as date_dernieres_infos 
    FROM 
      public.ddadtcontrat 
    where 
      dispositif_politique in ('64', '65') 
    group by 
      num_contrat
  ) tmp on (
    ddadtcontrat.num_contrat = tmp.num_contrat 
    and ddadtcontrat.date_dernieres_infos = tmp.date_dernieres_infos
  ) 
  inner join dadeh.ddadtemployeur_assure on (
    ddadtcontrat.id_employeur_assure = ddadtemployeur_assure.id
  ) 
  inner join dadeh.ddadtemployeur on (
    ddadtemployeur_assure.id_employeur = ddadtemployeur.id
  ) 
  inner join dadeh.ddadtassure on (
    ddadtemployeur_assure.id_assure = ddadtassure.id
  ) 
where 
  dispositif_politique in ('64', '65')


	

CREATE table public.dgefp_contrat_employeur_assure_filtre AS 
select 
  ddadtcontrat.id, 
  id_employeur_assure, 
  date_debut_contrat, 
  statut_conventionnel, 
  statut_rc, 
  pcs_ese, 
  code_complement_pcs_ese, 
  libelle_emploi, 
  nature_contrat, 
  dispositif_politique, 
  ddadtcontrat.num_contrat, 
  date_fin_previsionnelle, 
  unite_mesure, 
  quotite_categorie, 
  quotite, 
  modalite_temps, 
  complement_base, 
  ccn, 
  regime_maladie, 
  id_lieu_travail, 
  regime_vieillesse, 
  motif_recours, 
  code_caisse_conges_payes, 
  travailleur_etranger, 
  taux_frais_professionnels, 
  statut_emploi, 
  motif_exclusion_dsn, 
  code_affectation_ac, 
  num_interne, 
  type_gestion_ac, 
  date_adhesion, 
  date_convention_gestion, 
  num_convention_gestion, 
  code_gestionnaire_risque, 
  code_metier, 
  regime_risque_accident_travail, 
  code_risque_accident_travail, 
  positionnement_cc, 
  code_statut_categoriel_apecita, 
  taux_accident_travail, 
  salarie_tpartiel_cotis_tplein, 
  remuneration_pourboir, 
  id_lieu_etab_utilisateur, 
  num_certification_sociale, 
  num_label, 
  num_licence_entrep_spectacle, 
  num_objet_spectacle, 
  statut_organisateur_spectacle, 
  date_fin_contrat, 
  motif_rupture, 
  dernier_jour_travaille, 
  ddadtcontrat.date_dernieres_infos, 
  mod_decl_fin_cont_usage, 
  activite_partielle, 
  statut_boeth, 
  mise_a_dispo_ext, 
  cat_classement_finale, 
  college_cnieg, 
  complement_dispositif_public, 
  id_contrat_em, 
  ddadtcontrat.mois_declaration, 
  grade, 
  finess_geographique, 
  echelon, 
  coef_hierarchique, 
  flag_traitement_vue_donnee, 
  ddadtemployeur_assure.date_creation as ddadtemployeur_assure_date_creation, 
  ddadtemployeur_assure.date_dernieres_modif as ddadtemployeur_assure_date_dernieres_modif, 
  ddadtemployeur.siret, 
  ddadtemployeur.et_enseigne, 
  ddadtemployeur.et_code_apet, 
  ddadtemployeur.et_ad_num_et_libelle_voie, 
  ddadtemployeur.et_ad_code_postal, 
  ddadtemployeur.et_ad_localite, 
  ddadtemployeur.et_ad_code_pays, 
  ddadtemployeur.et_ad_code_distrib_etranger, 
  ddadtemployeur.et_ad_complement_localisation, 
  ddadtemployeur.et_ad_service_distrib, 
  ddadtemployeur.et_ad_code_insee_commune, 
  ddadtemployeur.et_effectif_fin_periode, 
  ddadtemployeur.et_remuneration_expatries, 
  ddadtemployeur.et_nature_juridique, 
  ddadtemployeur.et_date_cloture, 
  ddadtemployeur.et_categorie_juridique, 
  ddadtemployeur.siren, 
  ddadtemployeur.nic_siege, 
  ddadtemployeur.en_code_apen, 
  ddadtemployeur.en_raison_sociale, 
  ddadtemployeur.en_ad_num_et_libelle_voie, 
  ddadtemployeur.en_ad_code_postal, 
  ddadtemployeur.en_ad_localite, 
  ddadtemployeur.en_ad_code_pays, 
  ddadtemployeur.en_ad_code_distrib_etranger, 
  ddadtemployeur.en_ad_complement_localisation, 
  ddadtemployeur.en_ad_service_distrib, 
  ddadtemployeur.en_effectif_moyen, 
  ddadtemployeur.en_code_implantation, 
  ddadtemployeur.en_date_debut_cvae, 
  ddadtemployeur.en_date_fin_cvae, 
  ddadtemployeur.mois_declaration as ddadtemployeur_mois_declaration, 
  ddadtemployeur.et_code_conv_collec_principale, 
  ddadtemployeur.et_operateur_competence, 
  ddadtemployeur.en_code_conv_collec_applicable, 
  ddadtassure.num_immatriculation, 
  ddadtassure.type_immatriculation, 
  ddadtassure.nir_certifie, 
  ddadtassure.nom_usage, 
  ddadtassure.nom_famille, 
  ddadtassure.prenoms, 
  ddadtassure.sexe, 
  ddadtassure.date_naissance, 
  ddadtassure.date_dernieres_infos as ddadtassure_date_dernieres_infos, 
  ddadtassure.lieu_naissance, 
  ddadtassure.codification_ue, 
  ddadtassure.code_departement_naissance, 
  ddadtassure.code_pays_naissance, 
  ddadtassure.adresse_mail, 
  ddadtassure.nb_enfants_a_charge, 
  ddadtassure.date_naissance_certif_sngi, 
  ddadtassure.nom_famille_certif_sngi, 
  ddadtassure.prenoms_certif_sngi, 
  ddadtassure.nom_marital_certif_sngi, 
  ddadtassure.code_resultat_certif_sngi, 
  ddadtassure.indice_certif_sngi, 
  ddadtassure.commune_naissance_sngi, 
  ddadtassure.code_dpt_naissance_sngi, 
  ddadtassure.code_pays_naissance_sngi, 
  ddadtassure.date_nir_certif_sngi, 
  ddadtassure.immat_certifiee, 
  ddadtassure.niveau_formation_plus_eleve, 
  ddadtassure.niveau_diplome_prepare, 
  ddadtassure.date_deces_certif_sngi, 
  ddadtassure.num_immatriculation_chiffree, 
  ddadtassure.immat_certifiee_chiffree 
from 
  public.ddadtcontrat 
  inner join dadeh.ddadtemployeur_assure on (
    ddadtcontrat.id_employeur_assure = ddadtemployeur_assure.id
  ) 
  inner join dadeh.ddadtemployeur on (
    ddadtemployeur_assure.id_employeur = ddadtemployeur.id
  ) 
  inner join dadeh.ddadtassure on (
    ddadtemployeur_assure.id_assure = ddadtassure.id
  ) 
  inner join public.dgefp_num_immatriculation on (
    ddadtassure.num_immatriculation = dgefp_num_immatriculation.num_immatriculation
  );
  
CREATE table public.dgefp_versement_complet AS 
SELECT 
  id, 
  id_employeur_assure, 
  date_versement, 
  mois_declaration, 
  devise, 
  remuneration_nette_fiscale, 
  num_versement, 
  montant_net_verse, 
  rem_nette_fisc_pot, 
  montant_pas, 
  taux_rem_pos_stat, 
  type_erreur, 
  montant_non_imposable, 
  montant_abattement, 
  montant_soumis_pas, 
  date_creation, 
  type_taux_pas, 
  id_taux_pas, 
  numero_fraction 
FROM 
  dadeh.ddadtversement -- 94 413 845
  
  
  CREATE table public.dgefp_versement AS 
SELECT 
  ddadtversement.id, 
  ddadtversement.id_employeur_assure, 
  date_versement, 
  ddadtversement.mois_declaration, 
  devise, 
  remuneration_nette_fiscale, 
  num_versement, 
  montant_net_verse, 
  rem_nette_fisc_pot, 
  montant_pas, 
  taux_rem_pos_stat, 
  type_erreur, 
  montant_non_imposable, 
  montant_abattement, 
  montant_soumis_pas, 
  date_creation, 
  type_taux_pas, 
  id_taux_pas, 
  numero_fraction 
FROM 
  dadeh.ddadtversement 
  inner join (
    SELECT 
      id_employeur_assure, 
      max(mois_declaration) as mois_declaration 
    FROM 
      dadeh.ddadtversement 
    group by 
      id_employeur_assure
  ) tmp on (
    ddadtversement.id_employeur_assure = tmp.id_employeur_assure 
    and ddadtversement.mois_declaration = tmp.mois_declaration 
    and ddadtversement.num_versement = 1
  ) -- 7 259 598
  
  CREATE TABLE public.dgefp_contrat as 
SELECT 
  id, 
  id_employeur_assure, 
  date_debut_contrat, 
  statut_conventionnel, 
  statut_rc, 
  pcs_ese, 
  code_complement_pcs_ese, 
  libelle_emploi, 
  nature_contrat, 
  dispositif_politique, 
  num_contrat, 
  date_fin_previsionnelle, 
  unite_mesure, 
  quotite_categorie, 
  quotite, 
  modalite_temps, 
  complement_base, 
  ccn, 
  regime_maladie, 
  id_lieu_travail, 
  regime_vieillesse, 
  motif_recours, 
  code_caisse_conges_payes, 
  travailleur_etranger, 
  taux_frais_professionnels, 
  statut_emploi, 
  motif_exclusion_dsn, 
  code_affectation_ac, 
  num_interne, 
  type_gestion_ac, 
  date_adhesion, 
  date_convention_gestion, 
  num_convention_gestion, 
  code_gestionnaire_risque, 
  code_metier, 
  regime_risque_accident_travail, 
  code_risque_accident_travail, 
  positionnement_cc, 
  code_statut_categoriel_apecita, 
  taux_accident_travail, 
  salarie_tpartiel_cotis_tplein, 
  remuneration_pourboir, 
  id_lieu_etab_utilisateur, 
  num_certification_sociale, 
  num_label, 
  num_licence_entrep_spectacle, 
  num_objet_spectacle, 
  statut_organisateur_spectacle, 
  date_fin_contrat, 
  motif_rupture, 
  dernier_jour_travaille, 
  date_dernieres_infos, 
  mod_decl_fin_cont_usage, 
  activite_partielle, 
  statut_boeth, 
  mise_a_dispo_ext, 
  cat_classement_finale, 
  college_cnieg, 
  complement_dispositif_public, 
  id_contrat_em, 
  mois_declaration, 
  grade, 
  finess_geographique, 
  echelon, 
  coef_hierarchique, 
  flag_traitement_vue_donnee 
FROM 
  public.ddadtcontrat ;
  
  CREATE TABLE IF NOT EXISTS public.dgefp_num_immatriculation (
    num_immatriculation character varying COLLATE pg_catalog."default"
  );


